### ISSUE TITLE
Problem with using library

### ISSUE THREAD

**Issue by kwerner8** [slowli/externref#2] opened 2022-10-25 14:35 UTC
My goal is to compile a function written in Rust to WebAssembly which has a similar signature as your [example](https://github.com/slowli/externref#examples) `(externref, i32) -> externref`. Therefore, I want to use your library. But I have an issue by using it. I followed your [Usage ](https://github.com/slowli/externref#usage) example and get the following error message:

![MicrosoftTeams-image](https://user-images.githubusercontent.com/100682506/197801660-4e4a07e6-2021-4485-a329-9d19ff95f12c.png)
Can you help me there?

**Comment by slowli** [comment] 2022-10-27 11:16
Hi! Very glad that the library could be useful to someone besides me.

The library is not published yet on [crates.io](https://crates.io/) because it's not sufficiently tested as evidenced by #1; there were multiple miscompilation bugs I didn't take into account initially, and there quite a few remaining probably. The lack of a published version is the cause of the error you've encountered. Still, I plan to publish the library in the nearest week or so; after that, the ordinary dependency spec will work just fine. In the meanwhile, you can depend on [the git version of the library](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories):

```toml
[dependencies.externref]
version = "0.1.0"
git = "https://github.com/slowli/externref.git"
rev = "1320af1df269cb3df4710da1b3e4e9efb9b43ed3"
```

This is how I use the library in [another project](https://github.com/slowli/tardigrade/blob/7d95686cf47dbc4dd31c5a792e05c4304afd2383/e2e-tests/basic/Cargo.toml#L32); you may find it useful to look how it [is used there](https://github.com/slowli/tardigrade/blob/7d95686cf47dbc4dd31c5a792e05c4304afd2383/e2e-tests/basic/tests/integration/main.rs#L28).

**Comment by kwerner8** [comment] 2022-10-28 14:40
Thank you very much. I looked into your example but I am new to Rust and also its whole packaging and dependency system. 


My goal is to write a function in Rust and then compile it into a wasm file. Then I want to use this function as an export in a host code. This host code must be written in C++ for various reasons that cannot be changed.

So far, I have called the exported function directly and passed the input to it, similar to this [example](https://docs.wasmtime.dev/examples-c-gcd.html). I have used the [Wasmtime](https://docs.wasmtime.dev/examples-c-embed.html) runtime. But this way I can only pass [int/float](https://webassembly.github.io/spec/core/syntax/types.html) and not pass chars to the wasm-module, as they are not natively supported by WebAssembly. Therefore, I want to use `externref`. This way I can share a pointer to an object (such as a char or even a struct), pass this to the wasm-module which can modify it and then return it back to the host.
This is an [example for the host code](https://github.com/bytecodealliance/wasmtime/blob/main/examples/externref.c) in wasmtime which uses `externref` as an input/output and [this](https://github.com/bytecodealliance/wasmtime/blob/main/examples/externref.wat) is the corresponding wasm-module. The exported function in this wasm-module only returns the pointer given by the input of type `externref` but it has a similar function signature as your example. 

I want to compile Rust to a wasm-module similar to this, except it also modifies the data which `externref` points to instead of just returning the pointer as in the example of wasmtime.

Is it possible to compile such a wasm-module with your package?

**Comment by slowli** [comment] 2022-10-28 15:43
> Is it possible to compile such a wasm-module with your package?

This library is intended for Rust source code compiled into WASM, so it should work for your case. The host part can be in any programming language, although I've only really tested it with wasmtime (the original Rust library, not its C bindings).

I must say: the use case you're describing looks pretty weird in the sense that it could seemingly be solved without using `externref`s. If your goal is to *just* pass chars / byte buffers from the host to a WASM module, the conventional way to do so is to export the system allocator from the module, i.e., `alloc` / `realloc` / `free` equivalents. (`free` is needed if the ownership is not transferred from the host to the module.) The algorithm is as follows:

1. Call `alloc()` on the host with the necessary capacity, alignment etc., get a pointer to the WASM linear memory.
2. Copy bytes to the WASM linear memory at the pointer.
3. Pass the pointer and buffer length to the WASM module, e.g. via a module export.
4. In the module code: take ownership of the allocated bytes if required.

Here's rough Rust pseudo-code for the WASM module:

```rust
/// `alloc()` export. This version only allocates bytes, but this is good enough for `String`s as well.
#[no_mangle]
#[export_name = "alloc_bytes"]
pub extern "C" fn __alloc_bytes(capacity: usize) -> *mut u8 {
    let bytes = Vec::<u8>::with_capacity(capacity);
    let mut bytes = ManuallyDrop::new(bytes);
    // ^ Forgets about bytes (we'll take ownership of them in the export below).
    bytes.as_mut_ptr()
}

/// The "main" export that receives a `String` as an input.
#[no_mangle]
#[export_name = "receive_string"]
pub unsafe extern "C" fn __receive_string(string_ptr: *mut u8, string_len: usize) {
    let string = String::from_raw_parts(string_ptr, string_len, string_len);
    // ^ This takes ownership of the bytes passed from the host, so they are properly
    // deallocated on the module side.

    // Do something with `string`...
}
```

...and for the wasmtime host:

```rust
let alloc_bytes: TypedFunc<u32, u32> = // exported function extracted from the module
let memory: Memory = // WASM linear memory of the module
let mut ctx = // execution context
let string = "Hello, world!";
let ptr = alloc_bytes.call(ctx.as_context_mut(), string.len())?;
let ptr = usize::try_from(ptr).unwrap();
memory.write(ctx.as_context_mut(), ptr, string.as_bytes())?;
```

Furthermore, with `externref`s, you're likely to run into some problems:

> This way I can share a pointer to an object (such as a char or even a struct), pass this to the wasm-module which can modify it and then return it back to the host.

An `externref` is completely opaque from the WASM module perspective. You cannot dereference it in the module and cannot directly access or modify any data behind the pointer. The only thing you can do is to pass the `externref` back to the host and act on it this way. So, in your use case, you would likely need some WASM import functions that take a char `externref` as an argument and modify the underlying chars in certain ways; without these functions, an `externref` would be virtually useless.

**Comment by slowli** [comment] 2022-10-30 14:21
FYI, I [have published](https://crates.io/crates/externref) the initial version of the crate. Now, it can be specified in dependencies as `externref = "0.1.0"`.

**Comment by kwerner8** [comment] 2022-10-31 08:13
Thank you very much for your very detailed response and also your pseudo code. It really helped me a lot. I appreciate it! I will include this in my application.


> FYI, I [have published](https://crates.io/crates/externref) the initial version of the crate. Now, it can be specified in dependencies as `externref = "0.1.0"`.

Yes, the crate works like that now.

**Closed** 2022-11-01 11:58 UTC
